autocmd VimEnter *.py,*.sh,*.md TagbarOpen .

let g:tagbar_type_tf = {
  \ 'ctagstype': 'tf',
  \ 'kinds': [
    \ 'r:Resource',
    \ 'R:Resource',
    \ 'd:Data',
    \ 'D:Data',
    \ 'v:Variable',
    \ 'V:Variable',
    \ 'p:Provider',
    \ 'P:Provider',
    \ 'm:Module',
    \ 'M:Module',
    \ 'o:Output',
    \ 'O:Output',
    \ 'f:TFVar',
    \ 'F:TFVar'
  \ ]
\ }

if has('nvim')
lua << EOF
    require("claudecode").setup({
        auto_start = false
    })
    require("snacks").setup()
    require('telescope').setup{}
    require('telescope').load_extension('fzf')
EOF

  )
endif
