autocmd VimEnter *.py,*.sh,*.md TagbarOpen .

let g:tagbar_type_tf = {
  \ 'ctagstype': 'tf',
  \ 'kinds': [
    \ 'r:Resource',
    \ 'R:Resource',
    \ 'd:Data',
    \ 'D:Data',
    \ 'v:Variable',
    \ 'V:Variable',
    \ 'p:Provider',
    \ 'P:Provider',
    \ 'm:Module',
    \ 'M:Module',
    \ 'o:Output',
    \ 'O:Output',
    \ 'f:TFVar',
    \ 'F:TFVar'
  \ ]
\ }

if has('nvim')
lua << EOF
    require("claudecode").setup({
        auto_start = false
    })
    require("snacks").setup({
        picker = { enabled = true }
    })

    -- Terminal windows: black background
    vim.api.nvim_create_autocmd("ColorScheme", {
        pattern = "*",
        callback = function()
            vim.api.nvim_set_hl(0, "TermNormal", { bg = "#000000" })
        end,
    })
    vim.api.nvim_create_autocmd("TermOpen", {
        callback = function()
            vim.opt_local.winhighlight = "Normal:TermNormal"
        end,
    })

    -- Apply colorscheme after all plugins (including snacks) have initialized
    vim.api.nvim_create_autocmd("UIEnter", {
        once = true,
        callback = function()
            vim.cmd("colorscheme moonfly")
        end,
    })

    -- File/search keybindings via snacks picker
    vim.keymap.set("n", "<leader>ff", function() Snacks.picker.files() end,        { desc = "Find files" })
    vim.keymap.set("n", "<leader>fg", function() Snacks.picker.grep() end,         { desc = "Live grep" })
    vim.keymap.set("n", "<leader>fw", function() Snacks.picker.grep_word() end,    { desc = "Grep word under cursor" })
    vim.keymap.set("n", "<leader>fb", function() Snacks.picker.buffers() end,      { desc = "Find buffers" })
    vim.keymap.set("n", "<leader>fr", function() Snacks.picker.recent() end,       { desc = "Recent files" })
    vim.keymap.set("n", "<leader>fh", function() Snacks.picker.help() end,         { desc = "Search help tags" })
    vim.keymap.set("n", "<leader>gf", function() Snacks.picker.git_files() end,    { desc = "Find git files" })
    vim.keymap.set("n", "<leader>gc", function() Snacks.picker.git_log() end,      { desc = "Git log" })
EOF

endif
