#!/usr/bin/env python3

import os
import plistlib
import subprocess
from sys import argv,stderr

if not os.uname().sysname == "Darwin":
    print("golink cli only supported on MacOS", file=stderr)
    quit()

golink = "%20".join(argv[1:]) if len(argv) > 1 else "go"

HANDLERS_FILE = os.path.join(os.path.expanduser("~"), "Library", "Preferences",
                             "com.apple.LaunchServices", "com.apple.launchservices.secure.plist")

BROWSERS = {
    "com.google.chrome": "Google Chrome",
    "org.mozilla.firefox": "Firefox",
    "com.microsoft.edgemac": "Microsoft Edge"
}

with open(HANDLERS_FILE, "rb") as f:
    handlers = plistlib.load(f)

role = None
for handler in handlers["LSHandlers"]:
    if handler.get("LSHandlerURLScheme") == "https":
        role = handler["LSHandlerRoleAll"]

default_browser = BROWSERS.get(role)

if default_browser:
    app = os.path.join("/", "Applications", f"{default_browser}.app", "Contents", "MacOS", default_browser)
    subprocess.run([app, f"https://go/{golink}"])
else:
    print(f"Browser {role} not implemented yet.", file=stderr)
