#!/usr/bin/env bash
# shellcheck disable=SC1091

exit_bash() {
    cd "${DOTFILES_BASEDIR}" || return
    if [[ ! $(git status | grep 'nothing to commit') ]]; then
        echo "Committing changes to dotfiles before exit"
        commit_msg="Auto-add changes to dotfiles on shell exit

$(git status -b --untracked=all --porcelain)"
        git add .
        git commit -m "$commit_msg"
        git push
    fi
}

trap exit_bash EXIT

BASH_VERSION=$($BASH --version | awk '/bash/ {print $4}')
BASH_MAJOR_VERSION=$(echo "$BASH_VERSION" | awk -F'.' '{print $1}')

if [[ $BASH_MAJOR_VERSION -ge "4" ]]; then
    shopt -s globstar
fi

shopt -s histappend

# DOTFILES_BASEDIR is set in ~/.bashrc
[[ -f "${HOME}/.bashrc" ]] && source "${HOME}/.bashrc"

# update with remote changes before loading the remaining profile
if [[ -d "$DOTFILES_BASEDIR" ]]; then
    echo "Updating dotfiles"
    cd "$DOTFILES_BASEDIR"
    source "profiles/common/00_safety-zone.sh"
    GIT_SSH_COMMAND="ssh -i $HOME/.ssh/$(get_safe_value GITHUB_SSH_KEY)" git pull > /dev/null
    cd - > /dev/null
else
    echo "Unable to locate DOTFILES_BASEDIR: $DOTFILES_BASEDIR"
fi

# Use add-in scripts
re='[0-9]{2}_.*\.sh$'

for script in "${DOTFILES_BASEDIR}"/profiles/common/* "${DOTFILES_BASEDIR}"/profiles/active/*; do
    if [[ $script =~ $re ]]; then
        source "${script}"
    fi
done

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

echo
echo "Welcome to Bash $BASH_VERSION"
echo 


if [[ -f "${DOTFILES_BASEDIR}/profiles/active/profile.sh" ]]; then
    echo "Loading ${DOTFILES_PROFILE:=active} profile"
    . "${DOTFILES_BASEDIR}/profiles/active/profile.sh"
fi

if [[ -f "${DOTFILES_BASEDIR}/profiles/common/helpers/profile_utils.sh" ]]; then
    source "${DOTFILES_BASEDIR}/profiles/common/helpers/profile_utils.sh"
fi

export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# remove duplicates in PATH:
PATH=$(echo ${PATH} | /usr/bin/awk -v RS=: -v ORS=: '!($0 in a) {a[$0]; print}')
PATH="${PATH%:}"    # remove trailing colon
export PATH
